version: "3.8"

services:
  web:
    build:
      context: ./isafe-monitoring-react
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./isafe-monitoring-react/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./isafe-guard-backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"

    volumes:
      - monitoring-static:/app/src/main/static
      - monitoring-models:/app/src/models
    environment:
      - FLASK_ENV=production
      - HTTPS_ENABLED=true
      - DB_HOST=mongodb://mongodb:27017/
      - RTMP_MEDIA_SERVER=rtmp://mediamtx:1935
    networks:
      - app-network
    depends_on:
      - mongodb
      - mediamtx
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia

  mediamtx:
    image: mkghkk/mediamtx:latest
    container_name: mediamtx
    ports:
      - "1935:1935"
      - "8080:8080"
      - "8000:8000"
      - "8554:8554"
      - "8889:8889"
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

volumes:
  monitoring-static:
  monitoring-models:
  mongodb-data:

networks:
  app-network:
