version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80" # Only expose port 80 for HTTP
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # Nginx config
    depends_on:
      - web
      - backend
      - mediamtx
    networks:
      - app-network
    restart: always

  web:
    build:
      context: ./isafe-monitoring-react
      dockerfile: Dockerfile
    container_name: web
    expose:
      - "80" # Expose only for Nginx
    networks:
      - app-network
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./isafe-guard-backend
      dockerfile: Dockerfile
    container_name: backend
    expose:
      - "5000" # Expose only for Nginx
    ports:
      - "5000:5000"
    volumes:
      - monitoring-static:/app/src/main/static
      - monitoring-models:/app/src/models
    environment:
      - FLASK_ENV=production
      - HTTPS_ENABLED=false # HTTPS is disabled
      - DB_HOST=mongodb://mongodb:27017/
      - RTMP_MEDIA_SERVER=rtmp://mediamtx:1935
    networks:
      - app-network
    depends_on:
      - mongodb
      - mediamtx
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    restart: always

  mediamtx:
    image: mkghkk/mediamtx:latest
    container_name: mediamtx
    expose:
      - "8889" # Expose only for Nginx
    ports:
      - "1935:1935"
      - "8080:8080"
      - "8000:8000"
      - "8554:8554"
      - "8889:8889"
    networks:
      - app-network
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network
    restart: always

volumes:
  monitoring-static:
  monitoring-models:
  mongodb-data:

networks:
  app-network:
